---
- name: Get REST o/p
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:
    - name: print a sample message
      debug:
        msg: "Test playbook"

    - name: get value and print
      debug:
        var=finalname
     register: outputvalue
