---
- name: print message
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:
    - name: print a sample message
      debug:
        msg: "Hello punit is being printed"

    - name: ask for message
      debug:
        msg: "printing my name {{name}}"
